### ISSUE TITLE
Data loss: Structured remarks sections not showing up in remarks section of DocWriter UI.

### ISSUE THREAD

**Issue by MichaelNorman** [xamarin/DocWriter#25]
Repro:
1. Issue `ln -s <your-forms-repo-root>/Xamarin.Forms/docs/Xamarin.Forms.Core ~/XFCore/en` to allow DocWriter to open the XF.Core docs. (Unless https://github.com/xamarin/DocWriter/issues/14 has been fixed.)
2. Open `~/XFCore`–not a typo!–with DocWriter to view the docs.
3. Open the topic for `Xamarin.Forms.AbsoluteLayout`.

Expected:
1. The **Remarks:** section contains the text and code sample that are in the source file.
2. Source data is not lost without reasonable feedback when saving after editing.
3. Source data is not altered for fields that the writer does not touch.

Actual:
1. The **Remarks:** section is empty.
2.  DocWriter replaces the contents of the source file with what you enter in the Remarks when you save.
3. Further testing reveals that saving the file, even without authoring in the **Remarks:** section obliterates the source text.

Discussion:
Topics that do not have code examples seem to display. Additionally, all code examples in the Xamarin.Forms API document sources use CDATA blocks for the code at least because generics contain angle brackets. Because *all* of the Forms examples use CDATA, I was not able to determine if it is the code block itself, or the CDATA that causes this. (Or even the `<example>` tag!)

**Comment by MichaelNorman** [comment]
I just realized, having been too occupied with details before to notice this implication, but I *suspect* this bug means that DocWriter cannot be used on topics that meet whatever criteria cause this (`<example>`, `<code>`?, `CDATA`?), and that it isn't possible to tell *from within DocWriter* when you meet these criteria. In essence, DocWriter cannot be trusted as an editor until this is fixed.

**Comment by lobrien** [comment]
The problem occurs when an `<example>` element has a `<para>` child. (This is legal in the XSD.) 

The code for `DocWriter.RenderExample` calls `RenderPara` on the child nodes of the example. `RenderPara` does not admit a `para` and throws an `UnsupportedElementException`. This is caught in `DocWriter.ToHtml`, output to the console and swallowed.

**Comment by lobrien** [comment]
See also https://github.com/xamarin/DocWriter/issues/8 as this exception is currently not available to end-user.
