### ISSUE TITLE
Integrate DocWriter as an extension to VSCode

### ISSUE THREAD

**Issue by dend** [xamarin/DocWriter#28]
Would be great to integrate DocWriter as an extension to VSCode instead of a standalone tool - that will simplify integrations, as well as make it instantly cross-platform with minimal effort. The reason for this ask is grounded in the fact that our content teams (at docs.microsoft.com) rely entirely on VSCode as the primary editor, so we are assessing ways in which we can unify the workflows.

**Comment by lobrien** [comment]
How do you envision navigation working? DocWriter currently presents a treeview on the left that abstracts the file-system / XML-Element hierarchies. Is such a treeview supported within VSCode? If not, is there sufficient value in the editing UX to provide value? (I think the answer is "Yes," but it's worth asking.)

**Comment by dend** [comment]
@lobrien you should be able to just create a custom tree for the content representation, similar to how we treat the Git view.

See this PR:
https://github.com/Microsoft/vscode/pull/14048
